/**
 * Connect Support — Windows Native Client Agent
 * Electron Main Process
 *
 * Features:
 * - Invisible background agent (no taskbar, no dock, no visible window)
 * - System tray icon with connectivity indicator
 * - Full-screen approval dialog
 * - Real-time screen capture & streaming (10 FPS)
 * - Mouse & keyboard control via @nut-tree-fork/nut-js
 * - Privacy curtain (blank screen overlay window)
 * - Input lock (keyboard/mouse/touch block)
 * - Multi-monitor support & monitor switching
 * - Clipboard sharing & chunked file transfer
 * - Auto-start via Windows Registry Run key
 * - Auto-reconnect on disconnect
 * - Emergency exit: Ctrl+Alt+Escape
 */

"use strict";

// ── Squirrel install events (must be first) ───────────────────────────────────
if (require("electron-squirrel-startup")) process.exit(0);

const {
  app,
  BrowserWindow,
  Tray,
  Menu,
  nativeImage,
  ipcMain,
  globalShortcut,
  clipboard,
  screen,
  shell,
} = require("electron");

const path   = require("path");
const os     = require("os");
const fs     = require("fs");
const { io } = require("socket.io-client");

// ── Read config (embedded support code & server URL) ─────────────────────────
function loadConfig() {
  // Priority: command-line args → config.json → defaults
  const args = process.argv.slice(2);
  const argCode   = args.find((a) => a.startsWith("--code="))?.slice(7);
  const argServer = args.find((a) => a.startsWith("--server="))?.slice(9);

  const configPath = path.join(app.getPath("userData"), "config.json");
  let fileConfig = {};
  try {
    if (fs.existsSync(configPath)) {
      fileConfig = JSON.parse(fs.readFileSync(configPath, "utf8"));
    }
  } catch {}

  // Also check the install directory for the embedded config
  const installConfigPath = path.join(path.dirname(process.execPath), "config.json");
  let installConfig = {};
  try {
    if (fs.existsSync(installConfigPath)) {
      installConfig = JSON.parse(fs.readFileSync(installConfigPath, "utf8"));
    }
  } catch {}

  return {
    serverUrl: argServer || fileConfig.serverUrl || installConfig.serverUrl || "http://localhost:3000",
    supportCode: argCode || fileConfig.supportCode || installConfig.supportCode || "",
  };
}

let CONFIG = loadConfig();
const IS_DEV = process.argv.includes("--dev");
const IS_HIDDEN = process.argv.includes("--hidden") || !IS_DEV;

let setupWindow = null;

function showSetupWindow() {
  if (setupWindow && !setupWindow.isDestroyed()) {
    setupWindow.focus();
    return;
  }

  setupWindow = new BrowserWindow({
    width: 480,
    height: 430,
    resizable: false,
    title: "Connect Support Agent Setup",
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Connect Support Agent Setup</title>
  <style>*{box-sizing:border-box}body{margin:0;padding:32px;font-family:Segoe UI,system-ui,sans-serif;background:#0d1117;color:#e6edf3}h1{font-size:24px;margin:0 0 8px}p{color:#8b949e;line-height:1.5;margin:8px 0 24px}label{display:block;color:#8b949e;font-size:13px;margin-bottom:8px}input{width:100%;padding:13px;border:1px solid #30363d;border-radius:8px;background:#161b22;color:#fff;font-size:22px;letter-spacing:.25em;text-align:center}button{width:100%;margin-top:20px;padding:13px;border:0;border-radius:8px;background:#2563eb;color:#fff;font-size:15px;font-weight:600;cursor:pointer}button:disabled{opacity:.5}#error{color:#f87171;font-size:13px;min-height:20px;margin-top:12px;text-align:center}</style></head><body>
    <h1>Connect Support Agent</h1><p>Enter the 6-digit support code generated by your technician. This client will connect to the support server securely.</p>
    <label for="code">Support code</label><input id="code" maxlength="6" inputmode="numeric" autofocus><button id="connect">Connect Agent</button><div id="error"></div>
    <script>const code=document.getElementById('code'),button=document.getElementById('connect'),error=document.getElementById('error');code.addEventListener('input',()=>{code.value=code.value.replace(/\\D/g,'').slice(0,6)});button.addEventListener('click',async()=>{if(!/^\\d{6}$/.test(code.value)){error.textContent='Enter exactly 6 digits.';return}button.disabled=true;const result=await window.electronBridge.configure(code.value);if(!result.ok){error.textContent=result.error;button.disabled=false}});code.addEventListener('keydown',event=>{if(event.key==='Enter')button.click()});</script>
  </body></html>`;

  setupWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`);
  setupWindow.on("closed", () => { setupWindow = null; });
}

ipcMain.handle("configure-agent", async (_event, supportCode) => {
  if (!/^\d{6}$/.test(supportCode)) return { ok: false, error: "Enter exactly 6 digits." };
  const configPath = path.join(app.getPath("userData"), "config.json");
  const config = { serverUrl: CONFIG.serverUrl, supportCode };
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
  CONFIG = config;
  if (setupWindow && !setupWindow.isDestroyed()) setupWindow.close();
  connectSocket();
  updateTrayMenu();
  return { ok: true };
});

console.log("[Agent] Config:", CONFIG);

// ── State ─────────────────────────────────────────────────────────────────────
let tray             = null;
let approvalWindow   = null;
let privacyWindows   = [];   // one per monitor
let socket           = null;
let isConnected      = false;
let sessionActive    = false;
let streamInterval   = null;
let activeMonitor    = 0;
let inputLocked      = false;
let blankScreenOn    = false;
let reconnectTimer   = null;
let currentMediaKey  = "default-blue";

// ── Prevent second instances ──────────────────────────────────────────────────
const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
  process.exit(0);
}

// ── Windows Registry: auto-start ──────────────────────────────────────────────
function registerAutoStart() {
  if (process.platform !== "win32") return;
  try {
    const { execSync } = require("child_process");
    const exePath = process.execPath;
    const args = `--hidden --code=${CONFIG.supportCode} --server=${CONFIG.serverUrl}`;
    const cmd = `reg add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v "ConnectSupportAgent" /t REG_SZ /d "${exePath} ${args}" /f`;
    execSync(cmd, { windowsHide: true });
    console.log("[Agent] Auto-start registered");
  } catch (err) {
    console.error("[Agent] Failed to register auto-start:", err.message);
  }
}

function unregisterAutoStart() {
  if (process.platform !== "win32") return;
  try {
    const { execSync } = require("child_process");
    execSync(
      `reg delete "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v "ConnectSupportAgent" /f`,
      { windowsHide: true }
    );
  } catch {}
}

// ── Tray icon ─────────────────────────────────────────────────────────────────
function createTray() {
  // Create a simple 16x16 PNG tray icon programmatically
  const iconPath = path.join(__dirname, "..", "assets", "tray-icon.png");
  let icon;

  if (fs.existsSync(iconPath)) {
    icon = nativeImage.createFromPath(iconPath);
  } else {
    // Create a minimal 16x16 blue dot as fallback
    icon = nativeImage.createEmpty();
  }

  tray = new Tray(icon);
  updateTrayMenu();
  tray.setToolTip("Connect Support Agent");
}

function updateTrayMenu() {
  if (!tray) return;

  const statusLabel = isConnected
    ? sessionActive ? "● Session Active" : "● Online — Waiting"
    : "○ Disconnected";

  const menu = Menu.buildFromTemplate([
    { label: "Connect Support Agent", enabled: false },
    { label: statusLabel, enabled: false },
    { label: CONFIG.supportCode ? `Code: ${CONFIG.supportCode}` : "No code configured", enabled: false },
    { type: "separator" },
    {
      label: "Disconnect Session",
      enabled: sessionActive,
      click: () => emergencyExit(),
    },
    { type: "separator" },
    {
      label: "Uninstall & Remove",
      click: () => {
        unregisterAutoStart();
        app.quit();
      },
    },
    { type: "separator" },
    { label: "Quit Agent", click: () => emergencyExit() },
  ]);

  tray.setContextMenu(menu);
  tray.setToolTip(
    `Connect Support Agent\n${statusLabel}${CONFIG.supportCode ? `\nCode: ${CONFIG.supportCode}` : ""}`
  );
}

// ── Emergency exit ────────────────────────────────────────────────────────────
function emergencyExit() {
  console.log("[Agent] Emergency exit triggered");
  closeAllPrivacyWindows();
  if (socket) { socket.disconnect(); socket = null; }
  if (streamInterval) { clearInterval(streamInterval); streamInterval = null; }
  if (approvalWindow && !approvalWindow.isDestroyed()) approvalWindow.close();
  app.quit();
}

// ── Privacy / curtain windows ─────────────────────────────────────────────────
function getPrivacyHTML(mediaKey) {
  const styles = {
    "default-blue": `
      background: radial-gradient(ellipse at center, #0a1628 0%, #020c1b 100%);
      animation: pulse 4s ease-in-out infinite;
    `,
    "matrix-loop": `
      background: #000;
      /* Matrix rain effect via CSS */
    `,
    "maintenance-anim": `
      background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%);
      background-size: 400% 400%;
      animation: gradient-shift 8s ease infinite;
    `,
    "custom-video": `
      background: #000;
    `,
  };

  const chosen = styles[mediaKey] || styles["default-blue"];

  const matrixScript = mediaKey === "matrix-loop" ? `
    <canvas id="mc" style="position:fixed;inset:0;width:100%;height:100%;"></canvas>
    <script>
      const c = document.getElementById('mc');
      const ctx = c.getContext('2d');
      function resize() { c.width = window.innerWidth; c.height = window.innerHeight; }
      resize();
      window.addEventListener('resize', resize);
      const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*()';
      const fontSize = 14;
      let cols = Math.floor(c.width / fontSize);
      let drops = Array(cols).fill(1);
      function draw() {
        ctx.fillStyle = 'rgba(0,0,0,0.05)';
        ctx.fillRect(0,0,c.width,c.height);
        ctx.fillStyle = '#00ff41';
        ctx.font = fontSize + 'px monospace';
        for (let i=0;i<drops.length;i++) {
          const text = chars[Math.floor(Math.random()*chars.length)];
          ctx.fillText(text, i*fontSize, drops[i]*fontSize);
          if (drops[i]*fontSize > c.height && Math.random() > 0.975) drops[i] = 0;
          drops[i]++;
        }
      }
      setInterval(draw, 50);
    </script>
  ` : "";

  const videoElement = mediaKey === "custom-video" ? `
    <video autoplay loop muted playsinline style="position:fixed;inset:0;width:100%;height:100%;object-fit:cover;z-index:0;">
      <source src="maintenance.mp4" type="video/mp4" />
    </video>
  ` : "";

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Connect Support</title>
<style>
* { margin:0;padding:0;box-sizing:border-box; }
body {
  width:100vw; height:100vh; overflow:hidden;
  display:flex; align-items:center; justify-content:center;
  position:relative;
  ${chosen}
}
@keyframes pulse {
  0%,100% { opacity:1; }
  50%      { opacity:0.8; }
}
@keyframes gradient-shift {
  0%   { background-position: 0% 50%; }
  50%  { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}
.overlay {
  position:relative; z-index:10;
  text-align:center; padding:40px;
  background:rgba(0,0,0,0.6);
  border-radius:16px;
  border:1px solid rgba(255,255,255,0.1);
  backdrop-filter:blur(12px);
  max-width:600px;
}
.icon { font-size:64px; margin-bottom:20px; }
.title { font-size:28px; font-weight:700; color:#fff; margin-bottom:16px; font-family:system-ui,sans-serif; }
.subtitle { font-size:15px; color:rgba(255,255,255,0.7); line-height:1.7; font-family:system-ui,sans-serif; }
.badge {
  display:inline-block; margin-top:24px;
  padding:8px 20px; border-radius:99px;
  background:rgba(37,99,235,0.3); border:1px solid rgba(37,99,235,0.5);
  font-size:12px; color:#93c5fd; font-family:monospace;
}
#lock-banner {
  display:none; position:fixed; top:0; left:0; right:0;
  background:rgba(239,68,68,0.9); color:#fff;
  text-align:center; padding:12px;
  font-size:14px; font-weight:600; font-family:system-ui,sans-serif;
  z-index:999;
}
</style>
</head>
<body>
${videoElement}
${matrixScript}
<div id="lock-banner">🔒 Local Inputs Temporarily Paused — Your technician is in control</div>
<div class="overlay">
  <div class="icon">🔧</div>
  <div class="title">Maintenance in Progress</div>
  <div class="subtitle">
    Your technician is currently performing maintenance on your computer.<br/>
    Your screen is temporarily hidden for privacy and security.<br/>
    <strong style="color:#fff">This session is being performed with your permission.</strong>
  </div>
  <div class="badge">Connect Support · Authorized Remote Session</div>
</div>
<script>
  // Listen for messages from main process
  window.addEventListener('message', (e) => {
    if (e.data.type === 'toggle-lock-banner') {
      document.getElementById('lock-banner').style.display = e.data.show ? 'block' : 'none';
    }
  });
</script>
</body>
</html>`;
}

function openPrivacyWindows(mediaKey) {
  closeAllPrivacyWindows();
  const displays = screen.getAllDisplays();
  blankScreenOn = true;

  displays.forEach((display) => {
    const win = new BrowserWindow({
      x: display.bounds.x,
      y: display.bounds.y,
      width: display.bounds.width,
      height: display.bounds.height,
      frame: false,
      transparent: false,
      fullscreen: true,
      alwaysOnTop: true,
      skipTaskbar: true,
      focusable: false,
      resizable: false,
      movable: false,
      webPreferences: { nodeIntegration: false, contextIsolation: true },
      backgroundColor: "#000000",
      type: "toolbar",
    });

    const html = getPrivacyHTML(mediaKey || "default-blue");
    win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`);
    win.setAlwaysOnTop(true, "screen-saver");
    win.moveTop();
    privacyWindows.push(win);
  });
}

function closeAllPrivacyWindows() {
  blankScreenOn = false;
  privacyWindows.forEach((w) => {
    try { if (!w.isDestroyed()) w.close(); } catch {}
  });
  privacyWindows = [];
}

function updatePrivacyMedia(mediaKey) {
  currentMediaKey = mediaKey;
  if (!blankScreenOn) return;
  privacyWindows.forEach((w) => {
    if (!w.isDestroyed()) {
      const html = getPrivacyHTML(mediaKey);
      w.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`);
    }
  });
}

function setInputLock(locked) {
  inputLocked = locked;
  // Show/hide banner on all privacy windows
  privacyWindows.forEach((w) => {
    if (!w.isDestroyed()) {
      w.webContents.executeJavaScript(
        `window.postMessage({ type: 'toggle-lock-banner', show: ${locked} }, '*')`
      ).catch(() => {});
    }
  });
}

// ── Approval window ───────────────────────────────────────────────────────────
function showApprovalWindow(data) {
  if (approvalWindow && !approvalWindow.isDestroyed()) {
    approvalWindow.focus();
    return;
  }

  const { width, height } = screen.getPrimaryDisplay().workAreaSize;

  approvalWindow = new BrowserWindow({
    width: 480,
    height: 340,
    x: Math.round(width / 2 - 240),
    y: Math.round(height / 2 - 170),
    frame: true,
    resizable: false,
    alwaysOnTop: true,
    title: "Connect Support — Connection Request",
    skipTaskbar: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, "preload.js"),
    },
  });

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Connection Request</title>
<style>
* { margin:0;padding:0;box-sizing:border-box; }
body {
  font-family:system-ui,sans-serif; background:#0d1117; color:#e6edf3;
  display:flex; align-items:center; justify-content:center;
  height:100vh; padding:24px;
}
.card { text-align:center; max-width:400px; width:100%; }
.icon { font-size:48px; margin-bottom:16px; }
h2 { font-size:20px; font-weight:700; color:#fff; margin-bottom:8px; }
p { font-size:13px; color:#8b949e; line-height:1.6; margin-bottom:24px; }
.code { font-family:monospace; font-size:28px; font-weight:700; color:#3b82f6; letter-spacing:0.2em; margin-bottom:8px; }
.btns { display:flex; gap:12px; justify-content:center; }
button {
  padding:12px 28px; border-radius:10px; font-size:14px; font-weight:600;
  cursor:pointer; border:none; transition:opacity 0.2s;
}
button:hover { opacity:0.85; }
.approve { background:#2563eb; color:#fff; }
.reject  { background:#21262d; color:#8b949e; border:1px solid #30363d; }
.note { margin-top:16px; font-size:11px; color:#484f58; }
</style>
</head>
<body>
<div class="card">
  <div class="icon">🔐</div>
  <h2>Remote Support Request</h2>
  <p>Your technician is requesting permission to view and control your computer remotely.</p>
  <div class="code">${CONFIG.supportCode}</div>
  <p>Only approve if you contacted your technician and are expecting this request.</p>
  <div class="btns">
    <button class="approve" onclick="respond(true)">✓ Allow Access</button>
    <button class="reject"  onclick="respond(false)">✕ Decline</button>
  </div>
  <p class="note">You can disconnect at any time using Ctrl+Alt+Esc</p>
</div>
<script>
function respond(approved) {
  window.__RESPOND__(approved);
}
window.__RESPOND__ = function(approved) {
  // Communicate back via title change (preload bridge)
  document.title = approved ? 'APPROVED' : 'REJECTED';
  setTimeout(() => window.close(), 300);
};
</script>
</body>
</html>`;

  approvalWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`);

  // Monitor title changes as the IPC bridge
  approvalWindow.webContents.on("page-title-updated", (_e, title) => {
    if (title === "APPROVED") {
      socket.emit("client-approved-connection", {
        supportCode: CONFIG.supportCode,
        sessionId: data.sessionId,
      });
      sessionActive = true;
      updateTrayMenu();
      startScreenStream();
      approvalWindow.close();
    } else if (title === "REJECTED") {
      socket.emit("client-rejected-connection", { supportCode: CONFIG.supportCode });
      approvalWindow.close();
    }
  });

  approvalWindow.on("closed", () => { approvalWindow = null; });
}

// ── Screen streaming ──────────────────────────────────────────────────────────
async function startScreenStream() {
  if (streamInterval) clearInterval(streamInterval);

  let screenshot;
  try {
    screenshot = require("screenshot-desktop");
  } catch (err) {
    console.error("[Agent] screenshot-desktop not available:", err.message);
    return;
  }

  const displays = screen.getAllDisplays();
  const numMonitors = displays.length;

  // Inform tech about monitor count
  if (socket && socket.connected) {
    socket.emit("stream-frame", {
      supportCode: CONFIG.supportCode,
      frame: "",
      monitors: numMonitors,
      activeMonitor,
    });
  }

  streamInterval = setInterval(async () => {
    if (!socket || !socket.connected || !sessionActive) return;

    try {
      let imgBuffer;
      if (screenshot.listDisplays) {
        const screenList = await screenshot.listDisplays();
        const targetIdx = Math.min(activeMonitor, screenList.length - 1);
        imgBuffer = await screenshot({ screen: screenList[targetIdx]?.id, format: "jpg" });
      } else {
        imgBuffer = await screenshot({ format: "jpg" });
      }

      const base64 = imgBuffer.toString("base64");
      socket.emit("stream-frame", {
        supportCode: CONFIG.supportCode,
        frame: base64,
        monitors: numMonitors,
        activeMonitor,
      });
    } catch (err) {
      // Non-fatal: skip this frame
    }
  }, 100); // ~10 FPS
}

function stopScreenStream() {
  if (streamInterval) { clearInterval(streamInterval); streamInterval = null; }
}

// ── Mouse & Keyboard control ──────────────────────────────────────────────────
async function handleMouseEvent(data) {
  if (inputLocked) return;
  try {
    const { mouse, Button } = require("@nut-tree-fork/nut-js");
    mouse.config.autoDelayMs = 0;
    mouse.config.mouseSpeed = 2000;

    const displays = screen.getAllDisplays();
    const display = displays[Math.min(activeMonitor, displays.length - 1)];
    const absX = Math.round(data.x * display.bounds.width) + display.bounds.x;
    const absY = Math.round(data.y * display.bounds.height) + display.bounds.y;

    const { Point } = require("@nut-tree-fork/nut-js");

    if (data.type === "move") {
      await mouse.move([new Point(absX, absY)]);
    } else if (data.type === "click") {
      await mouse.move([new Point(absX, absY)]);
      const btn = data.button === 2 ? Button.RIGHT : Button.LEFT;
      await mouse.click(btn);
    } else if (data.type === "right-click") {
      await mouse.move([new Point(absX, absY)]);
      await mouse.click(Button.RIGHT);
    } else if (data.type === "double-click") {
      await mouse.move([new Point(absX, absY)]);
      await mouse.doubleClick(Button.LEFT);
    } else if (data.type === "mousedown") {
      await mouse.move([new Point(absX, absY)]);
      await mouse.pressButton(Button.LEFT);
    } else if (data.type === "mouseup") {
      await mouse.releaseButton(Button.LEFT);
    } else if (data.type === "scroll") {
      const { scroll } = require("@nut-tree-fork/nut-js");
      await scroll(data.deltaY > 0 ? 3 : -3);
    }
  } catch (err) {
    // nut-js may not be available in dev mode
    console.warn("[Agent] Mouse event error:", err.message);
  }
}

async function handleKeyboardEvent(data) {
  if (inputLocked) return;
  try {
    const { keyboard, Key } = require("@nut-tree-fork/nut-js");
    keyboard.config.autoDelayMs = 0;

    // Map standard key names to nut-js Key enum
    const keyMap = {
      Enter: Key.Return, Escape: Key.Escape, Backspace: Key.Backspace,
      Delete: Key.Delete, Tab: Key.Tab, Space: Key.Space,
      ArrowUp: Key.Up, ArrowDown: Key.Down, ArrowLeft: Key.Left, ArrowRight: Key.Right,
      Home: Key.Home, End: Key.End, PageUp: Key.PageUp, PageDown: Key.PageDown,
      F1: Key.F1, F2: Key.F2, F3: Key.F3, F4: Key.F4, F5: Key.F5,
      F6: Key.F6, F7: Key.F7, F8: Key.F8, F9: Key.F9, F10: Key.F10,
      F11: Key.F11, F12: Key.F12,
      Control: Key.LeftControl, Shift: Key.LeftShift, Alt: Key.LeftAlt,
      Meta: Key.LeftSuper, CapsLock: Key.CapsLock,
      Insert: Key.Insert, PrintScreen: Key.Print,
      NumLock: Key.NumLock, ScrollLock: Key.ScrollLock,
    };

    const modKeys = [];
    const mods = data.modifiers || [];
    if (mods.includes("ctrl"))  modKeys.push(Key.LeftControl);
    if (mods.includes("shift")) modKeys.push(Key.LeftShift);
    if (mods.includes("alt"))   modKeys.push(Key.LeftAlt);
    if (mods.includes("meta"))  modKeys.push(Key.LeftSuper);

    let nutKey = keyMap[data.key];
    if (!nutKey && data.key.length === 1) {
      // Single character — type it
      if (data.type === "keydown") {
        const keysToPress = [...modKeys];
        await keyboard.pressKey(...keysToPress);
        await keyboard.type(data.key);
        await keyboard.releaseKey(...modKeys.reverse());
      }
      return;
    }

    if (!nutKey) return;

    const allKeys = [...modKeys, nutKey];
    if (data.type === "keydown") {
      await keyboard.pressKey(...allKeys);
    } else if (data.type === "keyup") {
      await keyboard.releaseKey(...allKeys.reverse());
    }
  } catch (err) {
    console.warn("[Agent] Keyboard event error:", err.message);
  }
}

// ── Socket.io connection ──────────────────────────────────────────────────────
function connectSocket() {
  if (socket) { socket.disconnect(); socket = null; }
  if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; }

  if (!CONFIG.serverUrl || !CONFIG.supportCode) {
    console.error("[Agent] Missing serverUrl or supportCode in config");
    return;
  }

  console.log("[Agent] Connecting to:", CONFIG.serverUrl);

  socket = io(CONFIG.serverUrl, {
    transports: ["websocket", "polling"],
    reconnection: true,
    reconnectionAttempts: Infinity,
    reconnectionDelay: 2000,
    reconnectionDelayMax: 30000,
  });

  socket.on("connect", () => {
    console.log("[Agent] Socket connected:", socket.id);
    isConnected = true;
    updateTrayMenu();

    // Register with support code
    const computerName = os.hostname();
    const osInfo = `${os.type()} ${os.release()}`;
    socket.emit("register-client", {
      supportCode: CONFIG.supportCode,
      computerName,
      osInfo,
    });
  });

  socket.on("disconnect", (reason) => {
    console.log("[Agent] Socket disconnected:", reason);
    isConnected = false;
    sessionActive = false;
    stopScreenStream();
    updateTrayMenu();
  });

  socket.on("connect_error", (err) => {
    console.error("[Agent] Connection error:", err.message);
    isConnected = false;
    updateTrayMenu();
  });

  // ── Approval request from tech ────────────────────────────────────────────
  socket.on("approval-request", (data) => {
    console.log("[Agent] Approval request received:", data);
    showApprovalWindow(data);
  });

  // ── Tech disconnected ────────────────────────────────────────────────────
  socket.on("tech-disconnected", () => {
    console.log("[Agent] Tech disconnected");
    sessionActive = false;
    stopScreenStream();
    closeAllPrivacyWindows();
    setInputLock(false);
    updateTrayMenu();
  });

  // ── Mouse events from tech ────────────────────────────────────────────────
  socket.on("mouse-event", (data) => {
    handleMouseEvent(data).catch(console.error);
  });

  // ── Keyboard events from tech ─────────────────────────────────────────────
  socket.on("keyboard-event", (data) => {
    handleKeyboardEvent(data).catch(console.error);
  });

  // ── Blank screen (privacy curtain) ────────────────────────────────────────
  socket.on("toggle-blank-screen", ({ enabled }) => {
    console.log("[Agent] Blank screen:", enabled);
    if (enabled) {
      openPrivacyWindows(currentMediaKey);
    } else {
      closeAllPrivacyWindows();
    }
    updateTrayMenu();
  });

  // ── Change privacy media ──────────────────────────────────────────────────
  socket.on("change-privacy-media", ({ mediaKey }) => {
    currentMediaKey = mediaKey;
    updatePrivacyMedia(mediaKey);
  });

  // ── Input lock ────────────────────────────────────────────────────────────
  socket.on("toggle-input-lock", ({ enabled }) => {
    console.log("[Agent] Input lock:", enabled);
    setInputLock(enabled);
  });

  // ── Monitor switch ────────────────────────────────────────────────────────
  socket.on("switch-monitor", ({ monitorIndex }) => {
    activeMonitor = monitorIndex;
    console.log("[Agent] Switched to monitor:", monitorIndex);
  });

  // ── Clipboard (tech → client) ─────────────────────────────────────────────
  socket.on("clipboard-sync", ({ content, direction }) => {
    if (direction === "to-client") {
      clipboard.writeText(content);
    } else {
      // Push local clipboard to tech
      const text = clipboard.readText();
      socket.emit("clipboard-sync", {
        supportCode: CONFIG.supportCode,
        content: text,
        direction: "to-tech",
      });
    }
  });

  // ── File chunk (tech → client) ────────────────────────────────────────────
  const incomingFiles = new Map();
  socket.on("file-chunk", (data) => {
    if (data.direction !== "upload") return; // Upload = from tech to us
    const { fileId, fileName, chunkIndex, totalChunks, chunk } = data;

    if (!incomingFiles.has(fileId)) {
      incomingFiles.set(fileId, { chunks: new Array(totalChunks), received: 0, fileName, totalChunks });
    }
    const file = incomingFiles.get(fileId);
    file.chunks[chunkIndex] = chunk;
    file.received++;

    if (file.received === totalChunks) {
      // Reconstruct file
      const binary = Buffer.from(file.chunks.join(""), "base64");
      const savePath = path.join(app.getPath("downloads"), fileName);
      fs.writeFileSync(savePath, binary);
      shell.showItemInFolder(savePath);
      incomingFiles.delete(fileId);
      console.log("[Agent] File received:", savePath);
    }
  });
}

// ── App lifecycle ─────────────────────────────────────────────────────────────
app.whenReady().then(() => {
  // Hide from dock on macOS, hide from taskbar on Windows
  if (process.platform === "darwin") app.dock?.hide();

  // Register auto-start
  registerAutoStart();

  // Create tray
  createTray();

  // Register emergency exit shortcut
  globalShortcut.register("CommandOrControl+Alt+Escape", () => {
    console.log("[Agent] Emergency exit shortcut triggered");
    emergencyExit();
  });

  // Connect to signaling server
  connectSocket();

  if (!CONFIG.supportCode) showSetupWindow();

  // In dev mode, show a minimal info window
  if (IS_DEV) {
    const devWin = new BrowserWindow({
      width: 500,
      height: 300,
      title: "Connect Support Agent — DEV MODE",
      webPreferences: { nodeIntegration: false, contextIsolation: true },
    });
    devWin.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(`
      <html><body style="font-family:system-ui;background:#0d1117;color:#e6edf3;padding:20px">
      <h2>Connect Support Agent — Dev Mode</h2>
      <p>Server: <b>${CONFIG.serverUrl}</b></p>
      <p>Code: <b style="color:#3b82f6;font-size:24px;letter-spacing:0.2em">${CONFIG.supportCode || "NOT SET"}</b></p>
      <p>Emergency exit: <code>Ctrl+Alt+Esc</code></p>
      </body></html>
    `)}`);
  }
});

app.on("window-all-closed", (e) => {
  // Prevent default quit — agent must stay in tray
  e.preventDefault();
});

app.on("before-quit", () => {
  globalShortcut.unregisterAll();
  stopScreenStream();
  closeAllPrivacyWindows();
});

app.on("will-quit", () => {
  globalShortcut.unregisterAll();
});
